services:
  postgres-exporter:
    image: ${IMAGE_NAME:-quay.io/prometheuscommunity/postgres-exporter}:${IMAGE_TAG:-latest}
    command:
      - --web.listen-address=${WEB_LISTEN_ADDRESS}
      - --log.level=${LOG_LEVEL}
    environment:
      DATA_SOURCE_URI:
      DATA_SOURCE_USER:
      DATA_SOURCE_PASS:
      PG_EXPORTER_WEB_TELEMETRY_PATH:
      PG_EXPORTER_DISABLE_DEFAULT_METRICS:
      PG_EXPORTER_DISABLE_SETTINGS_METRICS:
    networks:
      - postgres-net
      - metric-net
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-30s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-32M}

networks:
  postgres-net:
    name: ${POSTGRES_NET_NAME:-postgres-net}
    external: true

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    external: true
